### ISSUE TITLE
CTD When Fast-Traveling or going near to Lakeview Manor

### ISSUE THREAD

**Issue by LeDingus** [Kvitekvist/FUS#55]
What the title says.

**Comment by LeDingus** [comment]
No one?

**Comment by habitat91** [comment]
It is best to use our discord for support (https://discord.gg/RqaA2fqNu2), We don't know if you've changed anything or what steps happened to produce it as this hasn't been brought up by anyone else.

**Comment by habitat91** [comment]
woops dint mean to close it sorry

**Comment by LeDingus** [comment]
No worries, sure I'll use the discord for support, thanks for the link. I can tell you right away I downloaded the FUS modpack from Wabbajack and have not modified anything nor added new mods to the list. This started after 18hours of gameplay out of the blues.

**Comment by MariusKlug** [comment]
I tried it out extensively, and could not get a CTD at all anywhere there. I tend to think that this issue is resolved in the current beta, even though I don't know what the issue was. I also never bought Lakeview Manor, so there's that... But I'll close this for now, if it comes up again, feel free to open a new issue or complain on the discord :)
